sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js


cache:
  directories:
    - $HOME/.npm

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

install:
  - export CURRENT_PACKAGE=$(pwd)
  - cd ../
  - git clone https://github.com/jankapunkt/simpl-schema-factory.git
  - git clone https://github.com/jankapunkt/meteor-mocha-helpers.git
  - git clone https://github.com/jankapunkt/mongo-collection-instances.git
  - cd $CURRENT_PACKAGE/tests && npm install

script:
  - npm run testcli